Parameters:
  InstanceType:
    Description: This is the ec2 instance Type
    Type: String
    AllowedValues:
      - t2.micro
      - t2.small
  AZs:
    Description: Available AZs in the Region
    Type: "List<!GetAZs AWS::Region>"
  cider:
    Description: CIDR range for security group ingress rules
    Type: String
  IngressPorts:
    Description: Ports and ranges
    Type: Number
    MinValue: 1024
    MaxValue: 65535
Resources:
   myec2:
      Type: AWS::EC2::Instance
      Properties:
         ImageId: ami-0ff8a91507f77f867
         InstanceType: !Ref InstanceType
         AvailabilityZone: !Ref AZs
         KeyName: office_aws
         SecurityGroupIds:
             - !GetAtt ec2securitygroup.GroupId
         Tags:
           -
             Key: Env
             Value: Dev
         UserData:
           Fn::Base64: !Sub |
             #!/bin/bash -xe
             yum -y install httpd
             echo "<html><h1>This is my test web page in ${AWS::Region}!!</h1></html>" > /var/www/html/index.html
             service httpd restart
             chkconfig httpd on

   ec2securitygroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
         VpcId: vpc-f33c1b89
         GroupDescription: SG for web servers
         SecurityGroupIngress:
         - CidrIp: !Ref cider
           FromPort: !Ref IngressPorts
           IpProtocol: tcp
           ToPort:
         - CidrIp: !Ref cider
           FromPort: !Ref IngressPorts
           IpProtocol: tcp
           ToPort: !Ref IngressPorts
         - CidrIp: !Ref cider
           FromPort: !Ref IngressPorts
           IpProtocol: tcp
           ToPort: !Ref IngressPorts
