AWSTemplateFormatVersion: 2010-09-09
Resources:
  myvpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: 'true'
      EnableDnsSupport: 'true'
  sub1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref myvpc
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: 'true'
  sub2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref myvpc
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: 'false'
  igw:
    Type: AWS::EC2::InternetGateway

  igwAttach:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref igw
      VpcId: !Ref myvpc
  routeTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref myvpc
  routeIGW:
    Type: AWS::EC2::Route
    DependsOn: routeTable
    Properties:
      RouteTableId: !Ref routeTable
      GatewayId: !Ref igw
      DestinationCidrBlock: 0.0.0.0/0
  subnetAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref routeTable
      SubnetId: !Ref sub1
  mysg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref myvpc
      GroupDescription: my SG for webservers
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80
  myec2:
    Type: AWS::EC2::Instance
    Properties:
      SubnetId: !Ref sub1
      ImageId: ami-0ff8a91507f77f867
      InstanceType: t2.micro
      SecurityGroupIds:
        - !GetAtt mysg.GroupId
